apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  someKey: some value
  template:
    spec:
      containers:
        - name: envar-demo-container
          image: gcr.io/google-samples/node-hello:1.0
          env:
            - name: DEMO_GREETING
              value: "Hello from the environment"
            - name: SOME_NUMBER
              value: "8000"
            - name: A_LIST
              value: "1,2,3,4,5"
            - name: URL
              value: "http://tiago.me.uk"
